version: '{build}'

image: Visual Studio 2019

platform:
  - x64

install:
  - ps: Install-Product node 16 x64
  - node --version
  - npm --version
  - openssl version
  - python --version
  - ssh -V
  - pip -V
  - npm install
  - ./node_modules/.bin/electron-rebuild

build_script:
  - python build.py

test_script:
  - npm test

artifacts:
  - path: 'dist\*.zip'
    name: build

before_deploy:
  - ps: foreach($artifactName in $artifacts.keys) { $artifacts[$artifactName] }
